// Re-export из @pv/shared — single source of truth.
// Существующий код extension импортирует типы через './types' — оставляем для backward-compat.

export {
  ApiError,
  // Core DTOs
  type Tag,
  type TagDTO,
  type Collection,
  type CollectionDTO,
  type Prompt,
  type PaginatedPrompts,
  type PaginatedResponse,
  type Team,
  type TeamDTO,
  type TeamRole,
  type TeamDetail,
  type TeamMember,
  type TeamInvitation,
  type FeedbackRequest,
  type FeedbackResponse,
  type StreakResponse,
  type StreakDTO,
  type SearchResultItem,
  type SearchResponse,
  type Suggestion,
  type SuggestResponse,
  type MeResponse,
  type User,
  type UserRole,
  type UserStatus,
  type PinResult,
  type PromptVersion,
  type BadgeSummary,
  type Badge,
  type BadgeCategory,
  type BadgeListResponse,
  type PlanID,
  type Plan,
  type Subscription,
  type SubscriptionStatus,
  type UsageSummary,
  type TeamUsageSummary,
  type QuotaInfo,
  type Chain,
  type ChainDetail,
  type ChainStep,
  type ChainStepType,
  type ChainStepPreview,
  type ChainStepPromptSummary,
  type ChainConditions,
  type ConditionBranch,
  type ChainExecution,
  type ChainExecutionStatus,
  type ChainExecutionSummary,
  type ChainExecutionListResponse,
  type ChainSnapshot,
  type ChainListResponse,
  type VariableMapping,
  type VariableSource,
  type APIKey,
  type APIKeyListResponse,
  type CreatedAPIKey,
  type CreateAPIKeyRequest,
  type ShareLink,
  type PublicPrompt,
  type TrashPrompt,
  type TrashCollection,
  type TrashCounts,
  type TrashListResponse,
  type ChangelogEntry,
  type ChangelogResponse,
  type LinkedAccount,
  type UpdateProfileRequest,
  type ChangePasswordRequest,
  type AuthResponse,
  type AdminLoginStepResponse,
  type VerifyTOTPResponse,
  type TOTPEnrollResponse,
  type TOTPStatusResponse,
  type TokenPair,
  type UsageLogEntry,
  type CollectionResponse,
  type IncrementUsageResponse,
  isPlanID,
  asPlanID,
} from "@pv/shared/types"

// Legacy alias: ранее `SearchResult` в extension имел структуру массивов
// (как сейчас `SearchResponse` в shared). Сохраняем имя для backward-compat.
export type { SearchResponse as SearchResult } from "@pv/shared/types"
